services:
  klipper:
    image: mkuf/klipper:latest
    restart: unless-stopped
    # logging:
    # driver: none
    depends_on:
      init:
        condition: service_completed_successfully
    command: -I printer_data/run/klipper.tty -a printer_data/run/klipper.sock printer_data/config/printer.cfg -l printer_data/logs/klippy.log
    devices:
      - ${PRINTER}:/dev/ttyUSB0
    volumes:
      - ${CONFIG}/config:/opt/printer_data/config
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs

  moonraker:
    image: mkuf/moonraker:latest
    restart: unless-stopped
    privileged: true
    pid: host
    #logging:
    #driver: none
    depends_on:
      init:
        condition: service_completed_successfully
      klipper:
        condition: service_started
    volumes:
      - /dev/null:/opt/klipper/config/null
      - /dev/null:/opt/klipper/docs/null
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
      - moonraker-db:/opt/printer_data/database
      - ${CONFIG}/config:/opt/printer_data/config
    ports:
      - 7125:7125

  webcam:
    image: mkuf/ustreamer:latest
    restart: unless-stopped
    command: --host=0.0.0.0 --port=8080 --slowdown --device=/dev/webcam --resolution=1280x960 --format=MJPEG --desired-fps=30
    devices:
      - ${WEBCAM}:/dev/webcam
    ports:
      - 7225:8080

  webcam1:
    image: mkuf/ustreamer:latest
    restart: unless-stopped
    command: --host=0.0.0.0 --port=8080 --slowdown --device=/dev/webcam --resolution=1920x1080 --format=MJPEG --desired-fps=30
    devices:
      - ${WEBCAM1}:/dev/webcam
    ports:
      - 7226:8080

  fluidd:
    image: cadriel/fluidd:latest
    restart: unless-stopped
    ports:
      - 8010:80

  init:
    image: busybox:latest
    command: chown -R 1000:1000 /prind/config
    volumes:
      - ${CONFIG}:/prind
    labels:
      org.prind.service: init

volumes:
  run:
    driver_opts:
      type: tmpfs
      device: tmpfs
  gcode:
  moonraker-db:
  log:
    driver_opts:
      type: tmpfs
      device: tmpfs
